<a href="https://colab.research.google.com/github/kristybell/TensorFlow_Developer_Certificate/blob/main/00_TensorFlow_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# In this notebook, going to cover some of the most fundamental concpts of tensors using TensorFlow

More specifically, will cover:
* Introduction to tensors
* Getting information from tensors
* Manipulating tensor
* Tensors & NumPy
* Using @tf.function (a way to speed up regular Python functions)
* Using GPUs with TensorFlow (or TPUs)
* Exercises to try 

## Introduction to Tensors

In [3]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.7.0


In [4]:
# Create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [5]:
# Check the number of dimensions of a tensor (ndim stand for number of dimensions)
scalar.ndim

0

In [6]:
# Create a vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [7]:
# Check the dimension of our vector
vector.ndim

1

In [8]:
# Create a matrix (has more than 1 dimension)
matrix = tf.constant([[10,7],
                     [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [9]:
matrix.ndim

2

In [10]:
# Create another matrix
another_matrix = tf.constant([[10., 7.],                        # recall that placing period after number signifies a float
                              [3., 2.],
                              [8., 9.]], dtype = tf.float16)    # specify the data type with dtype parameter; will take up less space than an int32
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [11]:
# Find the number dimension of "another matrix"
another_matrix.ndim

2

In [12]:
# Create a tensor
tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6]],
                       [[7, 8, 9,],
                       [10, 11, 12]],
                       [[13, 14, 15],
                        [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [13]:
tensor.ndim

3

Definitions
* Scalar: a single number
* Vector: a number with direction (e.g. wind speed and direction)
* Matrix: a 2-dimensional array of numbers
* Tensor: an n-dimensional array of number (when "n" can be any number, a 0-dimensional tensor is a scalar, a 1-dimensional tensor is a vector)

### Creating tensors with `tf.Variable`

In [14]:
# Create the same tensor with tf.Variable() as above
changeable_tensor = tf.Variable([10, 7])    # allows for changes using .assign()
unchangeable_tensor = tf.constant([10, 7])  # DOES NOT allow for changes using .assign()
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [15]:
# Let's try changing one of the elements in the changeable tensor
# changeable_tensor[0] = 7
# changeable_tensor

In [16]:
# How about try .assign()
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [17]:
# Try to change the unchangeable_tensor
# unchangeable_tensor[0].assign(7)
# unchangeable_tensor

🔑 **Note:** Rarely in practice will one need to decide whether to use `tf.constant` or `tf.variable` to create tensors, as TensorFlow does this for us. However, if in doubt, usse `tf.constant` and change it later, if needed.

### Creating random tensors

Random tensors are tensors of some arbitrary size which contain random numbers.

In [18]:
# Create two random (but the same) tensors
random_1 = tf.random.Generator.from_seed(7)    # set seed for reproducibility
random_1 = random_1.normal(shape=(3, 2))
random_2 = tf.random.Generator.from_seed(7)
random_2 = random_2.normal(shape=(3, 2))

# Are they equal? FYI they should be (lol)
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.2878567 ],
        [-0.8757901 , -0.08857017],
        [ 0.69211644,  0.84215707]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.2878567 ],
        [-0.8757901 , -0.08857017],
        [ 0.69211644,  0.84215707]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

### Shuffle the order of elements in a tensor

In [19]:
# Shuffle a tensor (valuable for when you want to shuffle your data, so the inherent order does not affect learning)
not_shuffled = tf.constant([[10,7],
                            [3, 4],
                            [2, 5]])
# Shuffle our non-shuffled tensor; 
tf.random.shuffle(not_shuffled)    #shuffles along 1-dimension

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [20]:
# Shuffle our non-shuffled tensor AGAIN; 
tf.random.shuffle(not_shuffled)    #shuffles along 1-dimension

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 2,  5],
       [ 3,  4]], dtype=int32)>

In [21]:
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [22]:
# Set seed for reproducibility
tf.random.shuffle(not_shuffled,
                  seed = 42)  

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]], dtype=int32)>

In [23]:
tf.random.set_seed(42)     # global level seed
tf.random.shuffle(not_shuffled, seed=42)      # operation level seed  

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

🔨**Exercise:** Read through TensorFlow documentation on random seed generation: https://www.tensorflow.org/api_docs/python/tf/random/set_seed and practice writing 5 random tensors and shuffle them.

It looks like if we want our shuffled tensors to be in the same order, we have to use the glbal level random seed, as well as, the peration level random seed:
> If both the global and the operation seed are set: Both seeds are used in conjunction to determine the random sequence.

In [24]:
tf.random.set_seed(42)                           # global level seed
tf.random.shuffle(not_shuffled, seed=42)         # operational level seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

### Other ways to make tensors

In [25]:
# Create a tensor of ones with 10 rows and 7 columns
tf.ones([10, 7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [26]:
# Create a tensor of all zeroes with 3 rows and 4 columns
tf.zeros(shape=(3,4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

### Turn NumPy arrays into tensors

The main difference between NumPy arrays and TensorFlow tensors is that tensors can be run on a GPU (much faster for numerical computing).

In [27]:
# Can also turn NumPy arrays
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32)     # create a NumPy array between 1 and 25
numpy_A

# X = tf.constant(some_matrix)    # capital for matrix or tensor
# y = tf.constant(vector)    # lowercase for vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [28]:
# A NumPy array can be passed through tf.constant() to turn into a tensor
A = tf.constant(numpy_A, shape=(2, 3, 4))   # creates a tensor with 2 matrices, of 3 rows with 4 columns each
B = tf.constant(numpy_A)
A, B

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

In [29]:
# Remember that the shape of the tensor must equate to the number of elements in the NumPy array
np.count_nonzero(A)

24

In [30]:
# Try changing size so there is still 24 elements
A = tf.constant(numpy_A, shape=(3, 8))  # creates a tensor with 2 matrices, of 3 rows with 4 columns each
B = tf.constant(numpy_A)
A, B

(<tf.Tensor: shape=(3, 8), dtype=int32, numpy=
 array([[ 1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16],
        [17, 18, 19, 20, 21, 22, 23, 24]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

In [31]:
# Check the number of dimensions of NumPy array]
A.ndim

2

### Getting information from tensors

When dealing with tensors, be aware of the following attributes:

* Shape (tensor.shape)
* Rank  (tensor.ndim)
* Axis or Dimension   (tensor[0], tenso[:,1] ..)
* Size  (tf.size(tensor))


In [32]:
# Create a rank 4 tensor (4 dimensions)
rank_4_tensor = tf.zeros(shape=[2, 3, 4, 5])   # 2 clusters, consisting of 3 matrices of 4 rows and 5 columns each
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [33]:
rank_4_tensor[0]   # outputs the first cluster

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [34]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [35]:
# Check size
2 * 3 * 4 * 5

120

In [36]:
# Get various attributes of our tensor
print("Datatype of every element:", rank_4_tensor.dtype)
print("Number of dimensions (rank):", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along the 0 axis:", rank_4_tensor.shape[0])
print("Elements along the last axis:", rank_4_tensor.shape[-1])
print("Total number of elements in our tensor:", tf.size(rank_4_tensor))
print("Total number of elements in our tensor:", tf.size(rank_4_tensor).numpy())

Datatype of every element: <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of tensor: (2, 3, 4, 5)
Elements along the 0 axis: 2
Elements along the last axis: 5
Total number of elements in our tensor: tf.Tensor(120, shape=(), dtype=int32)
Total number of elements in our tensor: 120


### Indexing tensors

Tensors can be indexed just like Python lists.

In [37]:
some_list = [1, 2, 3, 4]
some_list

[1, 2, 3, 4]

In [38]:
# Get the first 2 elements of each dimensions
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [39]:
some_list[:1]

[1]

In [40]:
rank_4_tensor.shape

TensorShape([2, 3, 4, 5])

In [41]:
# Get the first element for each dimension from each index ecept the final one
rank_4_tensor[:1, :,1 :1, :]

<tf.Tensor: shape=(1, 3, 0, 5), dtype=float32, numpy=array([], shape=(1, 3, 0, 5), dtype=float32)>

In [42]:
# Create a rank 2 tensor (2 dimensions)
rank_2_tensor = tf.constant([[10,7],
                              [3,4]])
rank_2_tensor.shape, rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [43]:
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [44]:
some_list, some_list[-1]

([1, 2, 3, 4], 4)

In [45]:
# Get the last item of each of row of our rank 2 tensor
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [46]:
# Add in extra dimension to our rank 2 tensor
rank_3_tensor = rank_2_tensor[..., tf.newaxis]   #tf.newaxis --> insert another dimension  and "..." every axis before
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [47]:
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [48]:
# Alternative to tf.newaxis
tf.expand_dims(rank_2_tensor, axis = -1)    # "-1" means to expand the final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [49]:
  tf.expand_dims(rank_2_tensor, axis=0)     # expand the 0-axis

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

In [50]:
# Get the first 2 elements of each dimension
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

 ### Manipulating Tensors (Tensor Operations)

 **Basic Operations**

 `+`, `-`, `*`, `/`

  **Built-In Functions**
  
  `tf.add`, `tf.subtract`, `tf.multiply`, `tf.divide`

In [51]:
# Can add values to a tensor using the addition operator
tensor = tf.constant([[10, 7], 
                      [3, 4]])
tensor + 10, tensor                    # will add '10' to each element without changing the tensor

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[20, 17],
        [13, 14]], dtype=int32)>, <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4]], dtype=int32)>)

In [52]:
# Multiplication also works
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [53]:
# Subtraction
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [54]:
# We can use the tensorflow built-in function too
tf.multiply(tensor, 10)    # same as 'tensor * 10', but built-in functions are FASTER than using operator

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [55]:
tensor   # still unchanged

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

**Matrix Multiplication**

In Machine Learning, matrix multiplication is one of the most common tensor operations. 

(Matrix MultiplicationCalculator: matrixmultiplication.xyz)

`tf.matmul()`

There are two rules tensors (or matrices) need to fulfil if we are going to matrix multiply them:
1. The inner dimensions must match
2.The resulting matrix has the shape of the outer dimensions

In [56]:
# Matrix multiplication in tensorflow
print(tensor)
tf.matmul(tensor, tensor)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [57]:
tensor, tensor

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4]], dtype=int32)>, <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4]], dtype=int32)>)

In [58]:
tensor * tensor   # Is not going to output an actual dot product result; instead multiply each element by the corresponding element

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  49],
       [  9,  16]], dtype=int32)>

In [59]:
# Matrix multiplication with Python operator #@#
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [60]:
tensor.shape

TensorShape([2, 2])

In [61]:
# Create a tensor (3, 2) tensor
X = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])

# Create another (3, 2) tensor
Y = tf.constant([[7, 8],
                 [9, 10],
                 [11, 12]])
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [62]:
# Try to matrix multiply tensors of same shape
# tf.matmul(X,Y)    #won't work because inner shape do not match

📑 **Resource** Information and examples of matrix multiplication: https://www.mathisfun.com/algebra/matrix-multiplying.html

In [63]:
# Change the shape of Y
tf.reshape(Y, shape=(2, 3)), Y     # prints out to reshaped Y and Y matrices

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[ 7,  8,  9],
        [10, 11, 12]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [64]:
# CHeck that the inner shapes match
X.shape, tf.reshape(Y, shape=(2,3)).shape

(TensorShape([3, 2]), TensorShape([2, 3]))

In [65]:
# Try matrix multiplication X by reshape Y
tf.matmul(X, tf.reshape(Y, shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [66]:
# Also can be written as
X @ tf.reshape(Y, shape=(2,3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [67]:
# Check if reshaping X instead would work
tf.matmul(tf.reshape(X, shape=(2,3)), Y)    # will work, but the output will be different because will give a 2x2 matrix instead of a 3x2 matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]], dtype=int32)>

In [68]:
tf.reshape(X, shape=(2,3)).shape, Y.shape

(TensorShape([2, 3]), TensorShape([3, 2]))

In [69]:
# The same can be done with transpose 
X, tf.transpose(X), tf.reshape(X, shape=(2,3))

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>)

In [70]:
# Try matrix multiplication with transpose rather than reshape
tf.matmul(tf.transpose(X), Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

**The Dot Product**

Matrix multiplication is also referred to as the dot product.

You can perform matrix multiplication using:
* `tf.matmul()`
* `tf.tensordot()`

In [71]:
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [72]:
# Perform the dot product on X and Y
tf.tensordot(tf.transpose(X), Y, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [73]:
# Sames as when we did tf.matmul(tf.transpose(X, Y))

In [74]:
# Perfrom matrix multiplication between X and Y(transposed)
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [75]:
# Perform matrix multiplication between X and Y (reshaped)
tf.matmul(X, tf.reshape(Y, shape= (2,  3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [76]:
# Check the values of Y, reshape Y and transposed Y to make sure the outputs make sense, and aren't silent errors
print("Normal Y: ")
print(Y, "\n")     # "\n" --> new line

print("Y reshaped to (2, 3): ")
print(tf.reshape(Y, (2, 3)), "\n")
print("Y transposed: ")
print(tf.transpose(Y))

Normal Y: 
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32) 

Y reshaped to (2, 3): 
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32) 

Y transposed: 
tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32)


In [77]:
tf.matmul(X, tf.transpose(Y))   # this is the correct way to do matrix multiplication of X dot Y

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

Generally, when performing matrix multiplication on two tensors and one of the axes doesn't line up, you will transpose (rather than reshape) one of the tensors to satisfy the matrix multiplication rules.

## Changing the datype of a tensor

In [78]:
# Create a new tensor with default datatype (float32)
B = tf.constant([1.7, 7.4])
B.dtype

tf.float32

In [79]:
C = tf.constant([7, 10])
C.dtype

tf.int32

In [80]:
# Change from float32 to float16 (reduced precision
D = tf.cast(B, dtype = tf.float16)
D, D.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>,
 tf.float16)

In [81]:
# Change from int32 to float 32
E = tf.cast(C, dtype = tf.float32)
E

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 7., 10.], dtype=float32)>

In [82]:
# Change from float32 to float16
E_float16 = tf.cast(E, dtype=tf.float16)
E_float16

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([ 7., 10.], dtype=float16)>

### Aggregating Tensors

Aggregating Tensors --> condensing from multiple values down to a small amount of values

In [83]:
# Get the absolute values
D = tf.constant([-7, -10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [84]:
# Get the absolute values
tf.abs(D)     # takes all the negative values and turns into a positive value

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

Forms of Aggregations:

* Minimum `tf.reduce_min()`
* Maximum  `tf.reduce_max()`
* Mean `tf.reduce_mean()`
* Sum  `tf.reduce_sum()`

In [85]:
# Create a random tensor for practicing forms of aggregation
# Tensor with values between 0 and 100 of size 50
E = tf.constant(np.random.randint(0, 100, size = 50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([ 0, 69, 28, 13, 59, 50, 81, 14, 82, 52,  2,  6, 11, 57, 85, 99, 90,
       19, 35, 59, 77, 72, 43, 98, 70, 66, 39, 99, 37,  7, 60, 23, 63, 28,
        7, 57, 52, 91, 50, 60,  9, 56, 25, 54,  8, 29, 58, 57, 73, 49])>

In [86]:
# Check the size, shape, and number of dimensions of the tensor
tf.size(E), E.shape, E.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [87]:
# Find the minimum of a tensor
tf.reduce_min(E)    # NumPy --> np.min()

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [88]:
# Find the maximum of a tensor
tf.reduce_max(E)     # NumPy --> np.max()

<tf.Tensor: shape=(), dtype=int64, numpy=99>

In [89]:
# Find the mean of a tensor
tf.reduce_mean(E)    # NumPy --> np.mean()

<tf.Tensor: shape=(), dtype=int64, numpy=48>

In [90]:
# Fin the sum of a tensor
tf.reduce_sum(E)    # NumPy --> np.sum()

<tf.Tensor: shape=(), dtype=int64, numpy=2428>

🛠 **Exercise:** Find the variance and standard deviation of the `E`tensor using TensorFlow method.

In [91]:
# To find the variance of a tensor, need access to tensor_proabbility
import tensorflow_probability as tfp

In [92]:
# Find the variance of a tensor
tfp.stats.variance(E)     # NumPy --> np.var(E)

<tf.Tensor: shape=(), dtype=int64, numpy=788>

In [93]:
# Find the standard deviation
tf.math.reduce_std(tf.cast(E, dtype=tf.float32))   # must change from int to float to use tf.math.reduce_std()

# NumPy --> np.std()

<tf.Tensor: shape=(), dtype=float32, numpy=28.075726>

In [94]:
# Find variance using tf.math.reduce_variance (must convert from into to float)
tf.math.reduce_variance(tf.cast(E, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=788.2464>

### Find the Positional Maximum and Minimum

In [95]:
# Create a new tensor for finding positional minimum and maximum
tf.random.set_seed(42)    # to allow for reproducibility; doesn't change numbers each time this line runs
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [96]:
# Find the positional maximum (gives the index of the max value)
tf.argmax(F)     # NumPy --> np.argmax()

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [97]:
# Index on our largest value position
F[tf.argmax(F)]           # returns the value of the maximum value based on the positional maximum

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [98]:
# Find the max value of F
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [99]:
# Check for equality (should be True)
F[tf.argmax(F)] == tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [100]:
# Find the position min
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [101]:
# Find the minimum using the positional minimum index
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

### Squeezing a Tensor (removing all single dimensions)

In [102]:
# Create a tensor to get started
tf.random.set_seed(42)     # allow for reproducibility
G = tf.constant(tf.random.uniform(shape=[50]), shape = (1, 1, 1, 1, 50))    # creates a tensor of size 50 consisting of random integers 
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [103]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [104]:
# Squeezing removes all single dimensions (1 dim) from a tensor
G_squeezed = tf.squeeze(G)
G_squeezed, G_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>, TensorShape([50]))

### One-hot Encoding Tensors

**Resource:** https://www.machinelearningmastery.com

In [105]:
# Create a list of indices
some_list = [0, 1, 2, 3]    # could be red, green, blue, purple

# One hot encode our list of indices
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [106]:
# Specify custom values for one hot encoding
tf.one_hot(some_list, depth=4, on_value="Yo, I love deep learning,", off_value ="I also like to dance")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'Yo, I love deep learning,', b'I also like to dance',
        b'I also like to dance', b'I also like to dance'],
       [b'I also like to dance', b'Yo, I love deep learning,',
        b'I also like to dance', b'I also like to dance'],
       [b'I also like to dance', b'I also like to dance',
        b'Yo, I love deep learning,', b'I also like to dance'],
       [b'I also like to dance', b'I also like to dance',
        b'I also like to dance', b'Yo, I love deep learning,']],
      dtype=object)>

### Squaring, log, square root

In [107]:
# Create a new tensor
H = tf.range(1, 10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [108]:
# Square it
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [109]:
# Find the square root (must convert integers to floats to run without error)
tf.sqrt(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.2360678, 2.4494896,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [110]:
# Find the log (must convert integers to floats to run without error)
tf.math.log(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

### Tensors and NumPy

TensorFlow interacts beautifully with NumPy arrays

🔑 **Note:** One of the main differences between a TensorFlow tensor and a NumPy array is that a TensorFlow tensor can be run on a GPU or TPU (for faster numerical processing).

In [111]:
# Create a tensor directly from a NumPy array
J = tf.constant(np.array([3., 7., 10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [112]:
# Convert our tensor back to a NumPy array
np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [113]:
# Convert tensor J to a NumPy array
J.numpy(), type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [114]:
# The default types of each are slightly different
numpy_J = tf.constant(np.array([3., 7., 10.]))
tensor_J = tf.constant([3., 7., 10.])

# Check the datatypes of each
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

### Finding Access to GPUs

CPU is not as fast as GPUs or TPUs.

To change to GPU --> Runtime > Change runtime type > Hardware Accelerator: GPU

In [115]:
import tensorflow as tf
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [116]:
!nvidia-smi   # Command to check which GPU we are using

Thu Jan 27 14:45:51 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 495.46       Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   42C    P0    27W /  70W |    266MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

🔑**Note:** If one has acces to a CUDA-enabled GPU, TensorFlow will automatically use it whenever posible.

**Extra-Curriculum Exercises to Try:**

1. Create a vector, scalar, matrix and tensor with values of your choosing using `tf.constant()`.
2. Find the shape, rank and size of the tensors you created in 1.
3. Create two tensors containing random values between 0 and 1 with shape `[5, 300]`.
4. Multiply the two tensors you created in 3 using matrix multiplication.
5. Multiply the two tensors you created in 3 using dot product.
6. Create a tensor with random values between 0 and 1 with shape `[224, 224, 3]`.
7. Find the min and max values of the tensor you created in 6 along the first axis.
8. Created a tensor with random values of shape `[1, 224, 224, 3]` then squeeze it to change the shape to `[224, 224, 3]`.
9. Create a tensor with shape `[10]` using your own choice of values, then find the index which has the maximum value.
10. One-hot encode the tensor you created in 9.

In [117]:
# 1. Create a vector, scalar, matrix, and tensor with values of your choosing using 'tf.constant()`
some_scalar = tf.constant(10)
some_vector = tf.constant([2, 4])
some_matrix = tf.constant([[6, 8],
                          [10,12]])
some_tensor = tf.constant([[[14, 16, 18],
                           [20, 22, 24]],
                          [[26, 28, 30],
                           [32, 34, 36]]])

print("A scalar: ", some_scalar)
print("A vector: ", some_vector)
print("A matrix: ", some_matrix)
print("A tensor: ", some_tensor)

A scalar:  tf.Tensor(10, shape=(), dtype=int32)
A vector:  tf.Tensor([2 4], shape=(2,), dtype=int32)
A matrix:  tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32)
A tensor:  tf.Tensor(
[[[14 16 18]
  [20 22 24]]

 [[26 28 30]
  [32 34 36]]], shape=(2, 2, 3), dtype=int32)


In [128]:
# 2. Find the shape, rank, and size of the tensors you created in 1.
print("Tensor Shape: ", some_tensor.shape)
print("Tensor Rank: ", some_tensor.ndim)
print("Tensor Size: ", tf.size(some_tensor).numpy())

Tensor Shape:  (2, 2, 3)
Tensor Rank:  3
Tensor Size:  12


In [132]:
# 3.Create two tensors containing random values between 0 and 1 with shape [5, 300]
tf.random.set_seed(42)   # for reproducibility
tensor_1 = tf.constant(tf.random.uniform(shape=[5, 300], minval=0, maxval=1))
tensor_2 = tf.constant(tf.random.uniform(shape=[5, 300], minval=0, maxval=1))
tensor_1, tensor_2

(<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.6645621 , 0.44100678, 0.3528825 , ..., 0.31410468, 0.7593535 ,
         0.03699052],
        [0.532024  , 0.29129946, 0.10571766, ..., 0.54052293, 0.31425726,
         0.2200619 ],
        [0.08404207, 0.03614604, 0.97732127, ..., 0.21516645, 0.9786098 ,
         0.00726748],
        [0.7396945 , 0.6653172 , 0.0787828 , ..., 0.7117733 , 0.07013571,
         0.9409125 ],
        [0.15861344, 0.12024033, 0.27218235, ..., 0.8824879 , 0.1432488 ,
         0.44135118]], dtype=float32)>,
 <tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.68789124, 0.48447883, 0.9309944 , ..., 0.6920762 , 0.33180213,
         0.9212563 ],
        [0.27369928, 0.10631859, 0.6218617 , ..., 0.4382149 , 0.30427706,
         0.51477313],
        [0.00920248, 0.37280262, 0.8177401 , ..., 0.56786287, 0.49201214,
         0.9892651 ],
        [0.88608265, 0.08672249, 0.12160683, ..., 0.91770685, 0.72545695,
         0.8280058 ],
        [0.36690

In [140]:
# 4. Multiply the two tensors created in 3 using matrix multiplication.
matr_mult = tf.matmul(tensor_1, tf.transpose(tensor_2))
matr_mult

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[80.333435, 73.40498 , 77.15961 , 73.98368 , 80.90053 ],
       [75.14637 , 68.80438 , 74.24303 , 71.84184 , 75.60205 ],
       [79.7594  , 75.64456 , 77.79758 , 74.748726, 80.55984 ],
       [75.085266, 69.06408 , 74.30776 , 72.27615 , 76.05667 ],
       [85.05689 , 74.26629 , 78.00687 , 74.886795, 83.13417 ]],
      dtype=float32)>

In [143]:
# 5. Multiply the two tensors create in 4 using dot product. 
dot_prod = tf.tensordot(tensor_1, tf.transpose(tensor_2), axes=1)
dot_prod

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[80.333435, 73.40498 , 77.15961 , 73.98368 , 80.90053 ],
       [75.14637 , 68.80438 , 74.24303 , 71.84184 , 75.60205 ],
       [79.7594  , 75.64456 , 77.79758 , 74.748726, 80.55984 ],
       [75.085266, 69.06408 , 74.30776 , 72.27615 , 76.05667 ],
       [85.05689 , 74.26629 , 78.00687 , 74.886795, 83.13417 ]],
      dtype=float32)>

In [145]:
# 6. Create a tensor with random values between 0 and 1 with shape [224, 224, 3].
tf.random.set_seed(42)   # for reproducibility
random_tensor = tf.constant(tf.random.uniform(shape=(224, 224, 3), minval=0, maxval=1))
random_tensor

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.6645621 , 0.44100678, 0.3528825 ],
        [0.46448255, 0.03366041, 0.68467236],
        [0.74011743, 0.8724445 , 0.22632635],
        ...,
        [0.42612267, 0.09686017, 0.16105258],
        [0.1487099 , 0.04513884, 0.9497483 ],
        [0.4393103 , 0.28527975, 0.96971095]],

       [[0.73308516, 0.5657046 , 0.33238935],
        [0.8838178 , 0.87544763, 0.56711245],
        [0.8879347 , 0.47661996, 0.42041814],
        ...,
        [0.7716515 , 0.9116473 , 0.3229897 ],
        [0.43050945, 0.83253574, 0.45549798],
        [0.29816985, 0.9639522 , 0.3316357 ]],

       [[0.41132426, 0.2179662 , 0.53570235],
        [0.5112119 , 0.6484759 , 0.8894886 ],
        [0.42459428, 0.20189774, 0.85781324],
        ...,
        [0.02888799, 0.3995477 , 0.11355484],
        [0.68524575, 0.04945195, 0.17778492],
        [0.97627187, 0.79811585, 0.9411576 ]],

       ...,

       [[0.9019445 , 0.27011132, 0.8090267 ],
        [0.32

In [148]:
# 7. Find the min and max values of the tensor you created in 6 along the first axis.
max, min = tf.reduce_max(random_tensor).numpy(), tf.reduce_min(random_tensor).numpy()
min, max

(3.5762787e-07, 0.999998)

In [151]:
# 8. Create a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].
tf.random.set_seed(42)   # for reproducibility
random_tensor_2 = tf.constant(tf.random.uniform(shape=(1, 224, 224, 3), minval= 0, maxval=1))

print("This is a random tensor: ", random_tensor_2)
print("And this is it squeezed: ", tf.squeeze(random_tensor_2))

This is a random tensor:  tf.Tensor(
[[[[0.6645621  0.44100678 0.3528825 ]
   [0.46448255 0.03366041 0.68467236]
   [0.74011743 0.8724445  0.22632635]
   ...
   [0.42612267 0.09686017 0.16105258]
   [0.1487099  0.04513884 0.9497483 ]
   [0.4393103  0.28527975 0.96971095]]

  [[0.73308516 0.5657046  0.33238935]
   [0.8838178  0.87544763 0.56711245]
   [0.8879347  0.47661996 0.42041814]
   ...
   [0.7716515  0.9116473  0.3229897 ]
   [0.43050945 0.83253574 0.45549798]
   [0.29816985 0.9639522  0.3316357 ]]

  [[0.41132426 0.2179662  0.53570235]
   [0.5112119  0.6484759  0.8894886 ]
   [0.42459428 0.20189774 0.85781324]
   ...
   [0.02888799 0.3995477  0.11355484]
   [0.68524575 0.04945195 0.17778492]
   [0.97627187 0.79811585 0.9411576 ]]

  ...

  [[0.9019445  0.27011132 0.8090267 ]
   [0.32395256 0.6672456  0.940673  ]
   [0.7166116  0.8860713  0.6777594 ]
   ...
   [0.8318608  0.39227867 0.68916583]
   [0.1599741  0.46428144 0.4656595 ]
   [0.8619243  0.24755931 0.33835268]]

  [[0.47

In [156]:
# 9. Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.
tf.random.set_seed(42)    # for reproducibility
A = tf.constant(tf.random.uniform(shape=[10], minval= 0, maxval=10))

print("I created this bomb tensor, look: ", A)
print("\nThis is the index of the maximum value in my bomb tensor: ", tf.argmax(A) )

I created this bomb tensor, look:  tf.Tensor(
[6.6456213  4.4100676  3.528825   4.6448255  0.33660412 6.8467236
 7.4011745  8.724445   2.2632635  2.2319686 ], shape=(10,), dtype=float32)

This is the index of the maximum value in my bomb tensor:  tf.Tensor(7, shape=(), dtype=int64)


In [163]:
# 10. One-hot encode the tensor you created in 9.

tf.one_hot(tf.cast(A, dtype=tf.int32), depth=10)

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>